### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by aleksasiriski** [DevOps-Nirvana/Universal-Kubernetes-Helm-Charts#6]
Does this helm chart support docker manifests with ARM support?

**Comment by AndrewFarley** [comment]
@aleksasiriski This currently doesn't limit to any specific architecture or operating system.  If you deployed this into your cluster, it would try to assign it to any available nodes.  If you need to use this with a multi-arch cluster I recommend you add a node selector...  for example...

```
nodeSelector:
  # For windows
  kubernetes.io/os: windows
  # For linux only
  kubernetes.io/os: windows
  # for ARM only
  kubernetes.io/arch: arm64
```

Hope that helps!
